# Parse the huge csv file generated by simu5g
# Get every kpi we are interested in and put it in a more friendly format
# INPUT: simu5g csv results file
# OUTPUT: another csv file but much better lmao

import pandas as pd

kpi_names = ["averageCqiDl:vector", "servingRSRP:vector", "servingRSRQ:vector",  "servingSINR:vector"]
kpi_vectors = {}
with open("data-simu5g.csv") as f:
    lines = f.readlines()

    for l in lines:
        # filter for lines with the kpis we want
        kpi = None
        for k in kpi_names: 
            if(k in l): 
                kpi = k
                break

        # the quotation mark are present only on lines where we have actual data, so we filter for them
        if(kpi and "\"" in l):
            quote_mark1 = l.find("\"")
            # remove everything except for the data
            # there is two lists of values, separated by quotation marks
            # first list is time, second is the values
            # they have a comma in between, so the easiest way to treat 
            # this is to just split and throw away the comma value lol
            time_vals,_, data_vector = l.strip()[quote_mark1+1:-1].split("\"")
            data = [float(x) for x in data_vector.split()]
            kpi_vectors[kpi] = data


# Write vals to a csv file thats gonna look so much better thant the previous one
df = pd.DataFrame.from_dict(kpi_vectors) 
df.to_csv ('clean_data.csv', index=False, header=True)
